name: Docker image update

on:
  push:
    paths:
      - 'app/**'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  TF_VAR_docker_password: ${{ secrets.DOCKER_PASSWORD }}
  TF_VAR_docker_username: ${{ secrets.DOCKER_USERNAME}}
  TF_VAR_private_key: ${{ secrets.PRIVATE_KEY }}
  TF_VAR_public_key: ${{ vars.SSH_PUBLIC_KEY }}
  TF_WORKING_DIR: '/terraform'
  
jobs:
  docker-update:
    name: 'Docker image update and push'
    runs-on: ubuntu-latest
    env:
      DOCKER_WORKING_DIR: ./app

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.DOCKER_WORKING_DIR }}

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.9.1
        
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{env.DOCKER_USERNAME}}
          password: ${{env.DOCKER_PASSWORD}}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: caiomoretti/my-library-image
  
  ec2-update:
    needs: docker-update
    uses: ./.github/workflows/ec2_update.yml
    secrets: inherit
