name: Terraform Workflow

on:
  push:
    branches:
      - main

env:
  TF_VAR_docker_password: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_KEY }}" >> ~/.aws/credentials


      - name: Create SSH Directory
        run: mkdir -p ~/.ssh
  
      - name: Check if SSH Key Exists
        id: check_ssh_key
        run: |
          if [ -f ~/.ssh/ssh-key ]; then
            echo "SSH key already exists"
            exit 1
          else
            echo "SSH key does not exist"
            exit 0
          fi
        continue-on-error: true
      
      - name: Generate SSH Key
        if: steps.check_ssh_key.outcome == 'success'
        run: |
          ssh-keygen -t rsa -f ~/.ssh/ssh-key
          chmod 600 ~/.ssh/ssh-key

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
