name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:

env:
  TF_VAR_docker_password: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  terraform_plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_KEY }}" >> ~/.aws/credentials


  terraform_destroy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_KEY }}" >> ~/.aws/credentials

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy --auto-approve

  terraform_apply:
    needs: terraform_plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_KEY }}" >> ~/.aws/credentials

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Apply
        run: terraform apply --auto-approve tfplan
